"""empty message

Revision ID: 5a2a39f2c5c7
Revises: 85de1b468c02
Create Date: 2023-02-16 18:21:43.286201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2a39f2c5c7'
down_revision = '85de1b468c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('money', 'account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('money', sa.Column('account', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
