"""empty message

Revision ID: f309dca37c7c
Revises: 5bbd99227c4b
Create Date: 2023-02-16 18:15:57.393327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f309dca37c7c'
down_revision = '5bbd99227c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('amount', sa.Integer(), nullable=True))
    op.drop_column('account', 'balance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('account', 'amount')
    # ### end Alembic commands ###
